### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by mcatanzaro** [WebPlatformForEmbedded/WPEBackend#27]
The name WPEBackend is problematic because it sounds like a backend, not a dependency of the actual backends. Even people who would be expected to have some experience with WPE fail to understand this, and that's reasonable since you would certainly expect it to be a backend.

I think we've discussed this in the past and decided to keep the name, but it's a bad name and should be corrected before the damage becomes too great. E.g. we have a Fedora package now `wpebackend`, but it's new: changing the package name now would be less problematic than waiting a couple years and then changing it.

**Comment by aperezdc** [comment]
If we are going to do this, I would do it before [v1.0.0](https://github.com/WebPlatformForEmbedded/WPEBackend/milestone/1) which we should be releasing soon. We would need a name and also I would like approvals by @zdobersek and @carlosgcampos (at least) before proceeding.

Do you have any suggestion for the name? I would rather go with something which describes what the library does, for example it could be `WPEInterface`, because it interfaces between WPE WebKit and backends (or similar).

**Comment by mcatanzaro** [comment]
WPEInterface, WPEBackendInterface, libwpe... I'm not picky.

**Comment by aperezdc** [comment]
Now that I think of it, using `libwpe` would nicely match the name of the `.pc` file, because it has always been a bit awkward to me that the library is named differently.

My suggestion is therefore to use `wpe-${APIVER}.pc` ≣ `libwpe-${APIVER}.so*`

@carlosgcampos @zdobersek: WDYT?
